console.log("Hi there!");
const botName = "teacherBot";
const greeting = `My name is ${botName}.`;
console.log(greeting);
const subject = "JavaScript";
const topic = "string";
const sentence = `Today, you will learn about $(topic) in ${subject}.`;
console.log(sentence);
const strLengthIntro = `Here is an example of using the word ${subject}.`;
console.log(strLengthIntro);
console.log(subject.length);
console.log(`Here is an example of using the length property on the word ${topic}.`);
console.log(topic.length);